name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e
          echo "Deployment started"
          cd /home/ubuntu/habits
          git pull origin main

          echo "Building frontend"
          cd front
          npm ci
          npm run build
          sudo cp -R build/* /var/www/html/
          
          echo "Updating backend"
          cd ../server
          npm ci
          pm2 restart all
          
          sudo systemctl restart nginx
          echo "Deployment finished"