name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Deployment started"
          cd /home/ubuntu/habits
          git pull origin main
    
          echo "Setting permissions"
          sudo chown -R ubuntu:ubuntu .
          sudo chmod -R 755 .
    
          echo "Building frontend"
          cd front
          rm -rf build
          npm ci
          npm run build
    
          echo "Copying build files"
          sudo cp -R build/* /var/www/html/
    
          echo "Updating backend"
          cd ../server
          npm ci
          pm2 restart all
    
          echo "Restarting Nginx"
          sudo systemctl restart nginx
          echo "Deployment finished"