name: Deploy to EC2

on:
  push:
    branches: [ main ]  # Adjust if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  

    - name: Install dependencies
      run: |
        cd front  # Adjust if your frontend is in a different directory
        npm ci
      
    - name: Build application
      run: |
        cd front
        npm ci
        npm run build

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/habits
          git pull origin main

          # Frontend deployment
          cd front
          npm ci
          npm run build
          sudo cp -R build/* /var/www/html/  

          # Backend deployment
          cd ../server
          npm ci
          pm2 restart all
          sudo systemctl restart nginx